export const data = JSON.parse("{\"key\":\"v-fb378c56\",\"path\":\"/start/waline.html\",\"title\":\"Waline\",\"lang\":\"zh-CN\",\"frontmatter\":{\"icon\":\"mark\",\"date\":\"2023-04-09T00:00:00.000Z\",\"category\":[\"教程\"],\"tag\":[\"Vercel\",\"插件\"],\"description\":\"Waline 本文将介绍如何在blog中使用Waline评论插件。 获取 APP ID 和 APP Key 请先 登录 或 注册 LeanCloud 国际版, 进入 控制台 后点击左下角 创建应用。创建应用后进入该应用，选择左下角的 设置 &gt; 应用Key，然后记下 APP ID,APP Key 和 Master Key。\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.github.io/start/waline.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Serendipity\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Waline\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Waline 本文将介绍如何在blog中使用Waline评论插件。 获取 APP ID 和 APP Key 请先 登录 或 注册 LeanCloud 国际版, 进入 控制台 后点击左下角 创建应用。创建应用后进入该应用，选择左下角的 设置 &gt; 应用Key，然后记下 APP ID,APP Key 和 Master Key。\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Serendipity\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Vercel\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"插件\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-04-09T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Waline\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2023-04-09T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Serendipity\\\",\\\"url\\\":\\\"https://mrhope.site\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"获取 APP ID 和 APP Key\",\"slug\":\"获取-app-id-和-app-key\",\"link\":\"#获取-app-id-和-app-key\",\"children\":[]},{\"level\":2,\"title\":\"配置仓库\",\"slug\":\"配置仓库\",\"link\":\"#配置仓库\",\"children\":[]},{\"level\":2,\"title\":\"配置主题\",\"slug\":\"配置主题\",\"link\":\"#配置主题\",\"children\":[]}],\"readingTime\":{\"minutes\":0.93,\"words\":279},\"filePathRelative\":\"start/waline.md\",\"localizedDate\":\"2023年4月9日\",\"excerpt\":\"<h1> Waline</h1>\\n<p>本文将介绍如何在blog中使用Waline评论插件。</p>\\n<h2> 获取 APP ID 和 APP Key</h2>\\n<p>请先 <a href=\\\"https://console.leancloud.app/login\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">登录</a> 或 <a href=\\\"https://console.leancloud.app/register\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">注册</a> LeanCloud 国际版, 进入 <a href=\\\"https://console.leancloud.app/apps\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">控制台</a> 后点击左下角 <a href=\\\"https://console.leancloud.app/apps\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">创建应用</a>。创建应用后进入该应用，选择左下角的 <code>设置</code> &gt; <code>应用Key</code>，然后记下 <code>APP ID,APP Key</code> 和 <code>Master Key</code>。</p>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
